apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedemo2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodedemo2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodedemo2
    spec:
      containers:
        - image: 495247221722.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
          imagePullPolicy: IfNotPresent
          name: nodedemo2
          ports:
            - containerPort: 3000
              protocol: TCP
---
  apiVersion: v1
  kind: Service
  metadata:
    name: nodedemo2
    namespace: default
  spec:
    ports:
      - name: http
        protocol: TCP
        port: 83
        targetPort: 3000
    selector:
      app: nodedemo2
    sessionAffinity: None
    type: NodePort
